baseURL = "https://thorsten-hake.com/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Thorsten Hake - IT Berater"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "de"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "Deutsch"

# Author config
[author]
  name = "Thorsten Hake"
  email = "mail@thorsten-hake.com"
  link = "https://thorsten-hake.com"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "profil"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Profil"
    url = "/profil"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "impressum"
    pre = ""
    post = ""
    name = "Impressum"
    url = "/impressum"
    title = ""
  
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params]
  title = "Thorsten Hake - IT Berater"
  dateFormat = "02.01.2006"
  description = "Meine Seite"
  [params.header.title]
    name = "Thorsten Hake - IT Berater"
  [params.home]
    [params.home.profile]
      title = "Thorsten Hake"
      subtitle = "<p>Freiberuflicher IT-Berater im JVM-Umfeld</p><p>Schauen Sie sich <a href=\"/profil\">mein Profil</a> an um mehr über mich zu erfahren."
      avatarURL = "/images/avatar.png"
      typeit = false
    [params.home.posts]
      enable = false
  [params.footer]
    since = 2023
  [params.social]
    GitHub = "thake"
    Linkedin = "thorsten-hake-3334a8262"
    Email = "mail@thorsten-hake.com"
    Phone = "+49 179 9078992"